version: 2
jobs:
  check:
    machine:
      - image: ubuntu-2204:current
    steps:
      - checkout
      - run: touch config.env
      - run: ./bin/check.sh
    environment:
      - PLAN_CODE: 24ska01

workflows:
  version: 2
  check:
    jobs:
      - check:
         context:
         - opsgenie
    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              ignore:
                - main
