import { Server } from "./components/types";

export const test: Server[] = [
  {
    planCode: "24ska01",
    name: "KS-A",
    category: "Kimsufi",
    cpu: "Intel i7-6700k 4.00 GHz",
    memory: "64 Go DDR4",
    storage: "1 x 480 Go SSD",
    bandwidth: "100 Mbit/s",
    price: 4.99,
    currencyCode: "EUR",
    status: "unavailable",
    datacenters: [],
  },
  {
    planCode: "24sk40",
    name: "KS-4",
    category: "Kimsufi",
    cpu: "Intel Xeon-E3 1230v6 3.50 GHz",
    memory: "16 Go DDR4",
    storage: "2 x 2000 Go HDD",
    bandwidth: "300 Mbit/s",
    price: 16.99,
    currencyCode: "EUR",
    status: "unavailable",
    datacenters: [],
  },
  {
    planCode: "24sk10",
    name: "KS-1",
    category: "Kimsufi",
    cpu: "Intel Xeon-D 1520 2.20 GHz",
    memory: "32 Go DDR4",
    storage: "2 x 2000 Go HDD",
    bandwidth: "300 Mbit/s",
    price: 16.99,
    currencyCode: "EUR",
    status: "unavailable",
    datacenters: [],
  },
  {
    planCode: "24sk30",
    name: "KS-3",
    category: "Kimsufi",
    cpu: "Intel Xeon-E3 1245 v5 3.50 GHz",
    memory: "32 Go DDR4",
    storage: "2 x 2000 Go HDD",
    bandwidth: "300 Mbit/s",
    price: 18.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["waw"],
  },
  {
    planCode: "24sk20",
    name: "KS-2",
    category: "Kimsufi",
    cpu: "Intel Xeon-D 1540 2.00 GHz",
    memory: "32 Go DDR4",
    storage: "4 x 2000 Go HDD",
    bandwidth: "300 Mbit/s",
    price: 18.99,
    currencyCode: "EUR",
    status: "unavailable",
    datacenters: [],
  },
  {
    planCode: "24sk50",
    name: "KS-5",
    category: "Kimsufi",
    cpu: "Intel Xeon-E3 1270 v6 3.80 GHz",
    memory: "32 Go DDR4",
    storage: "2 x 2000 Go HDD",
    bandwidth: "300 Mbit/s",
    price: 25.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["bhs", "fra", "gra", "rbx", "sbg", "waw"],
  },
  {
    planCode: "24ska01-syd",
    name: "KS-A",
    category: "Kimsufi",
    cpu: "Intel i7-6700k 4.00 GHz",
    memory: "32 Go DDR4",
    storage: "1 x 480 Go SSD",
    bandwidth: "",
    price: 25.99,
    currencyCode: "EUR",
    status: "unavailable",
    datacenters: [],
  },
  {
    planCode: "24skgame01",
    name: "KS-GAME",
    category: "Kimsufi",
    cpu: "Intel Core i7-7700K 4.20 GHz",
    memory: "32 Go DDR4",
    storage: "2 x 450 Go SSD",
    bandwidth: "300 Mbit/s",
    price: 34.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["bhs"],
  },
  {
    planCode: "24sk30-syd",
    name: "KS-3",
    category: "Kimsufi",
    cpu: "Intel Xeon-E3 1245 v5 3.50 GHz",
    memory: "32 Go DDR4",
    storage: "2 x 2000 Go HDD",
    bandwidth: "",
    price: 34.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["syd"],
  },
  {
    planCode: "24sk60",
    name: "KS-6",
    category: "Kimsufi",
    cpu: "AMD Epyc 7351p 2.40 GHz",
    memory: "128 Go DDR4",
    storage: "2 x 4000 Go HDD",
    bandwidth: "300 Mbit/s",
    price: 38.99,
    currencyCode: "EUR",
    status: "unavailable",
    datacenters: [],
  },
  {
    planCode: "24sk40-syd",
    name: "KS-4",
    category: "Kimsufi",
    cpu: "Intel Xeon-E3 1230v6 3.50 GHz",
    memory: "16 Go DDR4",
    storage: "2 x 2000 Go HDD",
    bandwidth: "",
    price: 39.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["syd"],
  },
  {
    planCode: "24sk20-syd",
    name: "KS-2",
    category: "Kimsufi",
    cpu: "Intel Xeon-D 1540 2.00 GHz",
    memory: "32 Go DDR4",
    storage: "2 x 2000 Go HDD",
    bandwidth: "",
    price: 39.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["syd"],
  },
  {
    planCode: "24skgame01-syd",
    name: "KS-GAME",
    category: "Kimsufi",
    cpu: "Intel Core i7-7700K 4.20 GHz",
    memory: "32 Go DDR4",
    storage: "2 x 450 Go SSD",
    bandwidth: "300 Mbit/s",
    price: 39.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["syd"],
  },
  {
    planCode: "24sk50-syd",
    name: "KS-5",
    category: "Kimsufi",
    cpu: "Intel Xeon-E3 1270 v6 3.80 GHz",
    memory: "32 Go DDR4",
    storage: "2 x 2000 Go HDD",
    bandwidth: "",
    price: 39.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["syd"],
  },
  {
    planCode: "24skstor01",
    name: "KS-STOR",
    category: "Kimsufi",
    cpu: "Intel Xeon-D 1521 2.40 GHz",
    memory: "",
    storage: "4 x 4000 Go HDD",
    bandwidth: "300 Mbit/s",
    price: 49.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["bhs", "fra", "gra", "lon", "rbx", "sbg", "waw"],
  },
  {
    planCode: "24sk30-sgp",
    name: "KS-3",
    category: "Kimsufi",
    cpu: "Intel Xeon-E3 1245 v5 3.50 GHz",
    memory: "32 Go DDR4",
    storage: "2 x 2000 Go HDD",
    bandwidth: "",
    price: 54.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["sgp"],
  },
  {
    planCode: "24skgame01-sgp",
    name: "KS-GAME",
    category: "Kimsufi",
    cpu: "Intel Core i7-7700K 4.20 GHz",
    memory: "32 Go DDR4",
    storage: "2 x 450 Go SSD",
    bandwidth: "300 Mbit/s",
    price: 54.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["sgp"],
  },
  {
    planCode: "24ska01-sgp",
    name: "KS-A",
    category: "Kimsufi",
    cpu: "Intel i7-6700k 4.00 GHz",
    memory: "32 Go DDR4",
    storage: "1 x 480 Go SSD",
    bandwidth: "",
    price: 54.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["sgp"],
  },
  {
    planCode: "24sk40-sgp",
    name: "KS-4",
    category: "Kimsufi",
    cpu: "Intel Xeon-E3 1230v6 3.50 GHz",
    memory: "16 Go DDR4",
    storage: "2 x 2000 Go HDD",
    bandwidth: "",
    price: 54.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["sgp"],
  },
  {
    planCode: "24sk20-sgp",
    name: "KS-2",
    category: "Kimsufi",
    cpu: "Intel Xeon-D 1540 2.00 GHz",
    memory: "32 Go DDR4",
    storage: "2 x 2000 Go HDD",
    bandwidth: "",
    price: 54.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["sgp"],
  },
  {
    planCode: "24sk50-sgp",
    name: "KS-5",
    category: "Kimsufi",
    cpu: "Intel Xeon-E3 1270 v6 3.80 GHz",
    memory: "32 Go DDR4",
    storage: "2 x 2000 Go HDD",
    bandwidth: "",
    price: 54.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["sgp"],
  },
  {
    planCode: "24sk70",
    name: "KS-7",
    category: "Kimsufi",
    cpu: "AMD Epyc 7451 2.30 GHz",
    memory: "128 Go DDR4",
    storage: "2 x 4000 Go HDD",
    bandwidth: "300 Mbit/s",
    price: 76.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["bhs", "fra", "gra", "lon", "rbx", "sbg", "waw"],
  },
  {
    planCode: "24sys01",
    name: "SYS-1",
    category: "So you Start",
    cpu: "Intel Xeon-E 2136 3.30 GHz",
    memory: "32 Go DDR4",
    storage: "2 x 512 Go SSD",
    bandwidth: "500 Mbit/s",
    price: 35.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["bhs", "fra", "gra", "lon", "rbx", "sbg", "waw"],
  },
  {
    planCode: "24sys02",
    name: "SYS-2",
    category: "So you Start",
    cpu: "Intel Xeon-D 2141I 2.20 GHz",
    memory: "32 Go DDR4",
    storage: "2 x 512 Go SSD",
    bandwidth: "500 Mbit/s",
    price: 44.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["bhs", "fra", "gra", "lon", "rbx", "sbg", "waw"],
  },
  {
    planCode: "24sys03",
    name: "SYS-3",
    category: "So you Start",
    cpu: "Intel Xeon-E 2288G 3.70 GHz",
    memory: "32 Go DDR4",
    storage: "2 x 960 Go SSD",
    bandwidth: "500 Mbit/s",
    price: 49.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["bhs", "fra", "gra", "lon", "rbx", "sbg", "waw"],
  },
  {
    planCode: "24sys01-syd",
    name: "SYS-1",
    category: "So you Start",
    cpu: "Intel Xeon-E 2136 3.30 GHz",
    memory: "32 Go DDR4",
    storage: "2 x 512 Go SSD",
    bandwidth: "",
    price: 54.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["syd"],
  },
  {
    planCode: "24sys01-sgp",
    name: "SYS-1",
    category: "So you Start",
    cpu: "Intel Xeon-E 2136 3.30 GHz",
    memory: "32 Go DDR4",
    storage: "2 x 512 Go SSD",
    bandwidth: "",
    price: 54.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["sgp"],
  },
  {
    planCode: "24sysgame01",
    name: "SYS-GAME-1",
    category: "So you Start",
    cpu: "AMD Ryzen 5 3600X 3.80 GHz",
    memory: "32 Go DDR4",
    storage: "2 x 512 Go SSD",
    bandwidth: "500 Mbit/s",
    price: 56.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["bhs", "fra", "gra", "lon", "sbg", "waw"],
  },
  {
    planCode: "24sysgame02",
    name: "SYS-GAME-2",
    category: "So you Start",
    cpu: "AMD Ryzen 7 3800X 3.90 GHz",
    memory: "64 Go DDR4",
    storage: "2 x 960 Go SSD",
    bandwidth: "500 Mbit/s",
    price: 79.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["bhs", "fra", "gra", "lon", "sbg", "waw"],
  },
  {
    planCode: "24sysstor01",
    name: "SYS-STOR",
    category: "So you Start",
    cpu: "AMD Ryzen 5 Pro 3600 3.60 GHz",
    memory: "32 Go DDR4",
    storage: "4 x 6000 Go HDD",
    bandwidth: "500 Mbit/s",
    price: 109.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["bhs", "fra", "gra", "lon", "rbx", "sbg", "waw"],
  },
  {
    planCode: "24sys04",
    name: "SYS-4",
    category: "So you Start",
    cpu: "AMD Epyc 7371 3.10 GHz",
    memory: "128 Go DDR4",
    storage: "2 x 960 Go SSD",
    bandwidth: "500 Mbit/s",
    price: 114.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["bhs", "fra", "gra", "lon", "rbx", "sbg", "waw"],
  },
  {
    planCode: "24sys05",
    name: "SYS-5",
    category: "So you Start",
    cpu: "Intel Xeon Silver 4214R 2.20 GHz",
    memory: "96 Go DDR4",
    storage: "2 x 960 Go SSD",
    bandwidth: "500 Mbit/s",
    price: 129.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["bhs", "fra", "gra", "lon", "rbx", "sbg", "waw"],
  },
  {
    planCode: "24sysstor01-mum",
    name: "SYS-STOR",
    category: "So you Start",
    cpu: "AMD Ryzen 5 Pro 3600 3.60 GHz",
    memory: "32 Go DDR4",
    storage: "4 x 6000 Go HDD",
    bandwidth: "",
    price: 134.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["ynm"],
  },
  {
    planCode: "24sysstor01-sgp",
    name: "SYS-STOR",
    category: "So you Start",
    cpu: "AMD Ryzen 5 Pro 3600 3.60 GHz",
    memory: "32 Go DDR4",
    storage: "4 x 6000 Go HDD",
    bandwidth: "",
    price: 134.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["sgp"],
  },
  {
    planCode: "25rises01",
    name: "RISE-S",
    category: "Rise",
    cpu: "AMD Ryzen 7 9700X 3.80 GHz",
    memory: "",
    storage: "2 x 512 Go SSD",
    bandwidth: "1000 Mbit/s",
    price: 54.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["waw"],
  },
  {
    planCode: "24rise01",
    name: "RISE-1",
    category: "Rise",
    cpu: "Intel Xeon-E 2386G 3.50 GHz",
    memory: "32 Go DDR4",
    storage: "2 x 512 Go SSD",
    bandwidth: "1000 Mbit/s",
    price: 56.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["bhs"],
  },
  {
    planCode: "24rise02",
    name: "RISE-2",
    category: "Rise",
    cpu: "Intel Xeon-E 2388G 3.20 GHz",
    memory: "64 Go DDR4",
    storage: "2 x 512 Go SSD",
    bandwidth: "1000 Mbit/s",
    price: 64.99,
    currencyCode: "EUR",
    status: "unavailable",
    datacenters: [],
  },
  {
    planCode: "24risegame01",
    name: "RISE-GAME-1",
    category: "Rise",
    cpu: "AMD Ryzen 5 5600X 3.70 GHz",
    memory: "32 Go DDR4",
    storage: "2 x 512 Go SSD",
    bandwidth: "",
    price: 74.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["bhs", "fra", "gra", "lon", "sbg", "waw"],
  },
  {
    planCode: "24rise01-mum",
    name: "RISE-1",
    category: "Rise",
    cpu: "Intel Xeon-E 2386G 3.50 GHz",
    memory: "32 Go DDR4",
    storage: "2 x 512 Go SSD",
    bandwidth: "",
    price: 76.49,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["ynm"],
  },
  {
    planCode: "24risegame01-sgp",
    name: "RISE-GAME-1",
    category: "Rise",
    cpu: "AMD Ryzen 5 5600X 3.70 GHz",
    memory: "32 Go DDR4",
    storage: "2 x 512 Go SSD",
    bandwidth: "",
    price: 80.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["sgp"],
  },
  {
    planCode: "24risegame01-syd",
    name: "RISE-GAME-1",
    category: "Rise",
    cpu: "AMD Ryzen 5 5600X 3.70 GHz",
    memory: "32 Go DDR4",
    storage: "2 x 512 Go SSD",
    bandwidth: "",
    price: 80.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["syd"],
  },
  {
    planCode: "24rise01-sgp",
    name: "RISE-1",
    category: "Rise",
    cpu: "Intel Xeon-E 2386G 3.50 GHz",
    memory: "32 Go DDR4",
    storage: "2 x 512 Go SSD",
    bandwidth: "",
    price: 89.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["sgp"],
  },
  {
    planCode: "24rise03",
    name: "RISE-3",
    category: "Rise",
    cpu: "AMD Ryzen 9 5900X 3.70 GHz",
    memory: "64 Go DDR4",
    storage: "2 x 512 Go SSD",
    bandwidth: "1000 Mbit/s",
    price: 99.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["bhs", "fra"],
  },
  {
    planCode: "24risegame02",
    name: "RISE-GAME-2",
    category: "Rise",
    cpu: "AMD Ryzen 7 5800X 3.80 GHz",
    memory: "64 Go DDR4",
    storage: "2 x 960 Go SSD",
    bandwidth: "",
    price: 111.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["bhs", "fra", "gra", "lon", "sbg", "waw"],
  },
  {
    planCode: "24rise02-sgp",
    name: "RISE-2",
    category: "Rise",
    cpu: "Intel Xeon-E 2388G 3.20 GHz",
    memory: "64 Go DDR4",
    storage: "2 x 512 Go SSD",
    bandwidth: "",
    price: 112.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["sgp"],
  },
  {
    planCode: "24rise02-mum",
    name: "RISE-2",
    category: "Rise",
    cpu: "Intel Xeon-E 2388G 3.20 GHz",
    memory: "64 Go DDR4",
    storage: "2 x 512 Go SSD",
    bandwidth: "",
    price: 112.99,
    currencyCode: "EUR",
    status: "unavailable",
    datacenters: [],
  },
  {
    planCode: "24risegame02-sgp",
    name: "RISE-GAME-2",
    category: "Rise",
    cpu: "AMD Ryzen 7 5800X 3.80 GHz",
    memory: "64 Go DDR4",
    storage: "2 x 960 Go SSD",
    bandwidth: "",
    price: 120.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["sgp"],
  },
  {
    planCode: "24risegame02-syd",
    name: "RISE-GAME-2",
    category: "Rise",
    cpu: "AMD Ryzen 7 5800X 3.80 GHz",
    memory: "64 Go DDR4",
    storage: "2 x 960 Go SSD",
    bandwidth: "",
    price: 120.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["syd"],
  },
  {
    planCode: "24rise03-mum",
    name: "RISE-3",
    category: "Rise",
    cpu: "AMD Ryzen 9 5900X 3.70 GHz",
    memory: "64 Go DDR4",
    storage: "2 x 512 Go SSD",
    bandwidth: "",
    price: 161.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["ynm"],
  },
  {
    planCode: "24rise03-sgp",
    name: "RISE-3",
    category: "Rise",
    cpu: "AMD Ryzen 9 5900X 3.70 GHz",
    memory: "64 Go DDR4",
    storage: "2 x 512 Go SSD",
    bandwidth: "",
    price: 161.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["sgp"],
  },
  {
    planCode: "24risestor01",
    name: "RISE-STOR",
    category: "Rise",
    cpu: "AMD Ryzen 7 Pro 3700 3.60 GHz",
    memory: "32 Go DDR4",
    storage: "4 x 14000 Go HDD",
    bandwidth: "1000 Mbit/s",
    price: 164.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["gra", "rbx", "waw"],
  },
  {
    planCode: "24rise04",
    name: "RISE-4",
    category: "Rise",
    cpu: "AMD Epyc 7313 3.00 GHz",
    memory: "64 Go DDR4",
    storage: "2 x 960 Go SSD",
    bandwidth: "1000 Mbit/s",
    price: 174.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["bhs", "fra", "gra", "lon", "rbx", "sbg", "waw"],
  },
  {
    planCode: "24rise06",
    name: "RISE-6",
    category: "Rise",
    cpu: "Intel Xeon Gold 6312U 2.40 GHz",
    memory: "128 Go DDR4",
    storage: "2 x 960 Go SSD",
    bandwidth: "1000 Mbit/s",
    price: 209.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["bhs", "waw"],
  },
  {
    planCode: "24rise05",
    name: "RISE-5",
    category: "Rise",
    cpu: "AMD Epyc 7413 2.65 GHz",
    memory: "128 Go DDR4",
    storage: "2 x 960 Go SSD",
    bandwidth: "1000 Mbit/s",
    price: 209.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["bhs", "fra", "lon", "rbx", "sbg", "waw"],
  },
  {
    planCode: "24rise04-sgp",
    name: "RISE-4",
    category: "Rise",
    cpu: "AMD Epyc 7313 3.00 GHz",
    memory: "64 Go DDR4",
    storage: "2 x 960 Go SSD",
    bandwidth: "",
    price: 219.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["sgp"],
  },
  {
    planCode: "24risestor01-sgp",
    name: "RISE-STOR",
    category: "Rise",
    cpu: "AMD Ryzen 7 Pro 3700 3.60 GHz",
    memory: "32 Go DDR4",
    storage: "4 x 14000 Go HDD",
    bandwidth: "",
    price: 238.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["sgp"],
  },
  {
    planCode: "24risestor01-mum",
    name: "RISE-STOR",
    category: "Rise",
    cpu: "AMD Ryzen 7 Pro 3700 3.60 GHz",
    memory: "32 Go DDR4",
    storage: "4 x 14000 Go HDD",
    bandwidth: "",
    price: 238.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["ynm"],
  },
  {
    planCode: "24rise04-mum",
    name: "RISE-4",
    category: "Rise",
    cpu: "AMD Epyc 7313 3.00 GHz",
    memory: "64 Go DDR4",
    storage: "2 x 960 Go SSD",
    bandwidth: "",
    price: 273.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["ynm"],
  },
  {
    planCode: "24rise06-sgp",
    name: "RISE-6",
    category: "Rise",
    cpu: "Intel Xeon Gold 6312U 2.40 GHz",
    memory: "128 Go DDR4",
    storage: "2 x 960 Go SSD",
    bandwidth: "",
    price: 302.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["sgp"],
  },
  {
    planCode: "24rise05-sgp",
    name: "RISE-5",
    category: "Rise",
    cpu: "AMD Epyc 7413 2.65 GHz",
    memory: "128 Go DDR4",
    storage: "2 x 960 Go SSD",
    bandwidth: "",
    price: 302.99,
    currencyCode: "EUR",
    status: "unavailable",
    datacenters: [],
  },
  {
    planCode: "24rise05-mum",
    name: "RISE-5",
    category: "Rise",
    cpu: "AMD Epyc 7413 2.65 GHz",
    memory: "128 Go DDR4",
    storage: "2 x 960 Go SSD",
    bandwidth: "",
    price: 302.99,
    currencyCode: "EUR",
    status: "available",
    datacenters: ["ynm"],
  },
];
