name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
    tags:
      - v*

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: '1.26'

    - name: Run golangci-lint linter
      uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
      with:
        version: v2.12.2

    - name: Prepare go.list for nancy
      run: go list -json -deps ./... > go.list

    - name: Run nancy security check
      uses: sonatype-nexus-community/nancy-github-action@726e338312e68ecdd4b4195765f174d3b3ce1533 # v1.0.3
      with:
        nancyCommand: sleuth --guide-token ${{ secrets.OSSI_TOKEN }}

    - name: Run Tests
      run: go test -race ./...

    - name: Install cross-compilers for aarch64 # Only run on rlease
      if: github.ref_type == 'tag'
      run: |
        sudo apt-get install -y \
          gcc-aarch64-linux-gnu=4:13.2.0-7ubuntu1 \
          g++-aarch64-linux-gnu=4:13.2.0-7ubuntu1

    - name: Build and Release with GoReleaser # Only run on rlease
      if: github.ref_type == 'tag'
      uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
      with:
        args: release --clean
        version: v2.17.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BUILD_BRANCH: ${{ vars.BUILD_BRANCH }}
        BUILD_USER: ${{ vars.BUILD_USER }}
