name: compatibility_test

on:
  push:
    branches-ignore:
    - main

jobs:
  compatibility_test:
    strategy:
      fail-fast: false
      matrix:
        distribution: [ubuntu, debian, fedora, manjaro]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run test
      run: |
        cp config.env.example config.env
        test/run.sh ${{ matrix.distribution }}
