name: run

on:
  schedule:
    - cron: "* * * * *"
  push:
    branches-ignore:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run check
        run: |
          touch config.env
          ./bin/check.sh
        env:
          PLAN_CODE: 24ska01
          OPSGENIE_API_KEY: ${{ secrets.OPSGENIE_API_KEY }}
